name: deploy-function
on: [push]
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install deps
        run: pip install azureml-core azureml-contrib-functions
      - name: Build and push image
        run: deploy_image.sh
        working-directory: fn-topic-model
