name: pr

on:
  pull_request:
    branches:
      - master
    paths:
      - 'topicmodel/**'
      - 'fn-topic-model/**'

jobs:
  lint-and-test:
    environment: dev
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install deps
        run: pip install pylint pytest

      - name: Lint/Test topicmodel
        run: pylint *.py && pytest
        working-directory: 'topicmodel'

      - name: Lint/Test fn-topic-model
        run: pylint *.py && pytest
        working-directory: 'topicmodel'
